#!/bin/bash
if [[ $EUID -ne 0 ]]; then
  echo "You must be a root user" 2>&1
  exit 1
else
  echo "installing necessary files"
  apt update
  apt install gcc g++
  chmod 777 *
  clear
  echo "all done"
fi
